name: character_viewer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  adaptive_layout: 0.1.7
  android_id: 0.3.3
  cached_network_image: 3.3.0
  cached_repository:
    path: ./package/cached_repository
  collection: ^1.18.0
  cupertino_icons: 1.0.2
  device_info_plus: 9.0.3
  dio: 4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  go_router: 6.0.0
  injectable: 2.2.0
  internet_connection_checker: 1.0.0+1
  json_annotation: 4.7.0
  logger: 1.1.0
  package_info_plus: 4.1.0
  rxdart: 0.27.7
  uuid: 3.0.7

dev_dependencies:
  bloc_test: 9.1.1
  build_runner: 2.3.3
  flutter_flavorizr: 2.1.5
  flutter_gen_runner: 5.1.0+1
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  go_router_builder: 1.0.16
  injectable_generator: 2.1.3
  json_serializable: 6.5.4
  mockito: 5.4.2
  retrofit_generator: 4.2.0

flutter:
  uses-material-design: true

flavorizr:
  flavors:
    simpsons:
      app:
        name: "Simpsons Character Viewer"

      android:
        applicationId: "com.sample.simpsonsviewer"
      ios:
        bundleId: "com.sample.simpsonsviewer"

    wire:
      app:
        name: "The Wire Character Viewer"

      android:
        applicationId: "com.sample.wireviewer"
      ios:
        bundleId: "com.sample.wireviewer"
      macos:
        bundleId: "com.sample.wireviewer"